version: '3.3'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    container_name: postgres-HMS
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=HMS
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - database
