# Use the official Python base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the container
COPY . .

# Set the environment variables for the database connection
ENV DATABASE_URL=postgresql://username:password@host:port/database

# Expose the port on which the Flask app runs
EXPOSE 5000

# Start the Flask application
CMD [ "python", "app.py" ]
